# Google App Engine - Python Application Configurations
# https://developers.google.com/appengine/docs/python/config/appconfig

application: your-app-name
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$

# (!) The expires headers are set pretty far in the future. If you don't control
# versioning with filename-based cache busting, consider lowering the cache time
# for resources like CSS and JS to something like 1 week.

includes:
- app_static_handlers.yaml

# Entry Point
handlers:

# If you want a completely static site uncomment the following
# lines and remove the gae.py reference from below.
#
# # index files
# - url: /(.*)/
#   static_files: static/\1/index.html
#   upload: static/(.*)/index.html
#   expiration: "15m"
#
# # site root
# - url: /
#   static_files: static/index.html
#   upload: static/index.html
#   expiration: "15m"

- url: /.*
  script: gae.py
